# Generated by Django 6.0.1 on 2026-01-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jadval nomi')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('late_threshold_minutes', models.IntegerField(default=5, verbose_name='Kechikish chegarasi (daqiqa)')),
                ('early_leave_threshold_minutes', models.IntegerField(default=5, verbose_name='Erta ketish chegarasi (daqiqa)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standart jadval')),
            ],
            options={
                'verbose_name': 'Ish jadvali',
                'verbose_name_plural': 'Ish jadvallari',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('check_in', 'Kirish'), ('check_out', 'Chiqish')], max_length=20, verbose_name='Hodisa turi')),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qurilma ID')),
                ('card_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Karta raqami')),
                ('verify_mode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tekshirish usuli')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Harorat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Davomat yozuvi',
                'verbose_name_plural': 'Davomat yozuvlari',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='attendance__employe_d2a742_idx'), models.Index(fields=['timestamp'], name='attendance__timesta_01c0dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('first_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Birinchi kirish')),
                ('last_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi chiqish')),
                ('scheduled_start', models.TimeField(verbose_name='Rejalashtirilgan boshlanish')),
                ('scheduled_end', models.TimeField(verbose_name='Rejalashtirilgan tugash')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Kechikish (daqiqa)')),
                ('early_leave_minutes', models.IntegerField(default=0, verbose_name='Erta ketish (daqiqa)')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name="Qo'shimcha ish (daqiqa)")),
                ('total_work_minutes', models.IntegerField(default=0, verbose_name='Jami ish vaqti (daqiqa)')),
                ('status', models.CharField(choices=[('present', 'Kelgan'), ('absent', 'Kelmagan'), ('late', 'Kechikkan'), ('early_leave', 'Erta ketgan'), ('late_and_early', 'Kechikkan va erta ketgan'), ('half_day', 'Yarim kun'), ('on_leave', "Ta'tilda"), ('holiday', 'Dam olish kuni')], default='absent', max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='employees.employee', verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Kunlik davomat',
                'verbose_name_plural': 'Kunlik davomatlar',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_370344_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_0ead4a_idx'), models.Index(fields=['status'], name='attendance__status_ac56c5_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
