# Generated by Django 6.0.1 on 2026-01-16 12:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dam olish kunining nomi', max_length=100, verbose_name='Bayram nomi')),
                ('date', models.DateField(help_text='Dam olish kuni sanasi', verbose_name='Sana')),
                ('holiday_type', models.CharField(choices=[('national', 'Milliy bayram'), ('religious', 'Diniy bayram'), ('company', 'Kompaniya bayram'), ('other', 'Boshqa')], default='national', max_length=20, verbose_name='Bayram turi')),
                ('is_recurring', models.BooleanField(default=False, help_text="Bu bayram har yili bir xil sanada bo'ladimi", verbose_name='Har yili takrorlanadi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Dam olish kuni',
                'verbose_name_plural': 'Dam olish kunlari',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', "Yillik ta'til"), ('sick', 'Kasallik'), ('unpaid', "Haq to'lanmaydigan"), ('maternity', 'Dekret'), ('paternity', "Otalik ta'tili"), ('bereavement', 'Motam'), ('other', 'Boshqa')], max_length=20, verbose_name="Ta'til turi")),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('reason', models.TextField(help_text="Ta'til olish sababi", verbose_name='Sabab')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rad etish sababi')),
                ('attachment', models.FileField(blank=True, help_text="Qo'shimcha hujjat (kasallik varaqasi va h.k.)", null=True, upload_to='leave_requests/%Y/%m/', verbose_name='Ilova')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
            options={
                'verbose_name': "Ta'til so'rovi",
                'verbose_name_plural': "Ta'til so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['name'], 'verbose_name': 'Ish jadvali', 'verbose_name_plural': 'Ish jadvallari'},
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='att_emp_time_idx',
            old_name='attendance__employe_d2a742_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='att_timestamp_idx',
            old_name='attendance__timesta_01c0dc_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyattendance',
            new_name='daily_date_idx',
            old_name='attendance__date_370344_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyattendance',
            new_name='daily_emp_date_idx',
            old_name='attendance__employe_0ead4a_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyattendance',
            new_name='daily_status_idx',
            old_name='attendance__status_ac56c5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tanib olish ishonchliligi (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Ishonchlilik'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='mask_status',
            field=models.CharField(blank=True, choices=[('wearing', 'Niqobli'), ('not_wearing', 'Niqobsiz'), ('unknown', "Noma'lum")], help_text="Niqob taqilgan yoki yo'q", max_length=20, null=True, verbose_name='Niqob holati'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='photo_snapshot',
            field=models.ImageField(blank=True, help_text='Kirish/chiqish vaqtidagi rasm', null=True, upload_to='attendance/snapshots/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='raw_data',
            field=models.JSONField(blank=True, help_text="Qurilmadan kelgan to'liq JSON ma'lumot", null=True, verbose_name="Xom ma'lumot"),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Kim tasdiqlagan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_end',
            field=models.TimeField(blank=True, help_text='Tushlik tanaffusi tugash vaqti', null=True, verbose_name='Tushlik tugashi'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_start',
            field=models.TimeField(blank=True, help_text='Tushlik tanaffusi boshlanish vaqti', null=True, verbose_name='Tushlik boshlanishi'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='code',
            field=models.CharField(blank=True, help_text='Qisqa identifikator', max_length=20, null=True, unique=True, verbose_name='Jadval kodi'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Jadval faol yoki arxivlangan', verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='working_days',
            field=models.JSONField(default=list, help_text="Ish kunlari ro'yxati (0-6: Dushanba-Yakshanba)", verbose_name='Ish kunlari'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='card_no',
            field=models.CharField(blank=True, help_text='RFID karta raqami', max_length=50, null=True, verbose_name='Karta raqami'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='device_id',
            field=models.CharField(blank=True, help_text='Hikvision qurilma identifikatori', max_length=50, null=True, verbose_name='Qurilma ID'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(help_text='Davomat yozuvi tegishli hodim', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='event_type',
            field=models.CharField(choices=[('check_in', 'Kirish'), ('check_out', 'Chiqish')], help_text='Kirish yoki chiqish', max_length=20, verbose_name='Hodisa turi'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tana harorati (°C)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))], verbose_name='Harorat'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(db_index=True, help_text="Hodisa sodir bo'lgan vaqt", verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='verify_mode',
            field=models.CharField(blank=True, choices=[('face', 'Yuz tanish'), ('fingerprint', 'Barmoq izi'), ('card', 'RFID karta'), ('password', 'Parol'), ('mixed', 'Aralash')], help_text='Qanday usulda tekshirilgan', max_length=20, null=True, verbose_name='Tekshirish usuli'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(db_index=True, help_text='Davomat sanasi', verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='early_leave_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Necha daqiqa erta ketgan', verbose_name='Erta ketish (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='employee',
            field=models.ForeignKey(help_text='Davomat tegishli hodim', on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='employees.employee', verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='first_check_in',
            field=models.DateTimeField(blank=True, help_text='Shu kundagi birinchi kirish vaqti', null=True, verbose_name='Birinchi kirish'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='last_check_out',
            field=models.DateTimeField(blank=True, help_text='Shu kundagi oxirgi chiqish vaqti', null=True, verbose_name='Oxirgi chiqish'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Necha daqiqa kechikkan', verbose_name='Kechikish (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha izohlar", null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='overtime_minutes',
            field=models.PositiveIntegerField(default=0, help_text="Qo'shimcha ishlangan daqiqalar", verbose_name="Qo'shimcha ish (daqiqa)"),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='scheduled_end',
            field=models.TimeField(help_text="Ish tugashi kerak bo'lgan vaqt", verbose_name='Rejalashtirilgan tugash'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='scheduled_start',
            field=models.TimeField(help_text="Ish boshlanishi kerak bo'lgan vaqt", verbose_name='Rejalashtirilgan boshlanish'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Kelgan'), ('absent', 'Kelmagan'), ('late', 'Kechikkan'), ('early_leave', 'Erta ketgan'), ('late_and_early', 'Kechikkan va erta ketgan'), ('half_day', 'Yarim kun'), ('on_leave', "Ta'tilda"), ('holiday', 'Dam olish kuni'), ('sick_leave', 'Kasallik'), ('remote', 'Masofadan')], default='absent', help_text='Davomat holati', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='total_work_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Umumiy ishlangan daqiqalar', verbose_name='Jami ish vaqti (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='early_leave_threshold_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Necha daqiqadan keyin erta ketish hisoblanadi', validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Erta ketish chegarasi (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(help_text='Ish kunining tugash vaqti', verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Yangi hodimlar uchun standart jadval', verbose_name='Standart jadval'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='late_threshold_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Necha daqiqadan keyin kechikish hisoblanadi', validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Kechikish chegarasi (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='name',
            field=models.CharField(help_text='Ish jadvalining nomi', max_length=100, unique=True, verbose_name='Jadval nomi'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(help_text='Ish kunining boshlanish vaqti', verbose_name='Boshlanish vaqti'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['event_type'], name='att_event_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['device_id'], name='att_device_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'timestamp', 'device_id'), name='unique_attendance_record'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_daily_attendance'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='unique_holiday'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Hodim'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='leave_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_dates_idx'),
        ),
    ]
