# Generated by Django 6.0.1 on 2026-01-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HikvisionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qurilma nomi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('port', models.IntegerField(default=80, verbose_name='Port')),
                ('username', models.CharField(max_length=50, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='Parol')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seriya raqami')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Joylashuv')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Xatolik')], default='offline', max_length=20, verbose_name='Holat')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi sinxronizatsiya')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hikvision qurilma',
                'verbose_name_plural': 'Hikvision qurilmalar',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('partial', 'Qisman'), ('failed', 'Xatolik')], max_length=20, verbose_name='Holat')),
                ('records_fetched', models.IntegerField(default=0, verbose_name='Olingan yozuvlar')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Qayta ishlangan')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='hikvision.hikvisiondevice', verbose_name='Qurilma')),
            ],
            options={
                'verbose_name': 'Sinxronizatsiya logi',
                'verbose_name_plural': 'Sinxronizatsiya loglari',
                'ordering': ['-started_at'],
            },
        ),
    ]
