# Generated by Django 6.0.1 on 2026-01-16 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('hikvision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('get_device_info', "Qurilma ma'lumoti"), ('get_users', "Foydalanuvchilar ro'yxati"), ('get_events', "Hodisalar ro'yxati"), ('add_user', "Foydalanuvchi qo'shish"), ('delete_user', "Foydalanuvchi o'chirish"), ('sync_time', 'Vaqtni sinxronlash'), ('reboot', 'Qayta yuklash'), ('other', 'Boshqa')], max_length=30, verbose_name='Buyruq turi')),
                ('endpoint', models.CharField(help_text="So'rov yuborilgan URL yo'li", max_length=500, verbose_name='API endpoint')),
                ('http_method', models.CharField(default='GET', help_text='GET, POST, PUT, DELETE', max_length=10, verbose_name='HTTP metod')),
                ('request_data', models.JSONField(blank=True, help_text="Yuborilgan ma'lumotlar (JSON)", null=True, verbose_name="So'rov ma'lumotlari")),
                ('response_data', models.JSONField(blank=True, help_text='Qurilmadan kelgan javob (JSON)', null=True, verbose_name="Javob ma'lumotlari")),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP status kodi')),
                ('is_successful', models.BooleanField(default=False, help_text="Buyruq muvaffaqiyatli bajarildi yoki yo'q", verbose_name='Muvaffaqiyatli')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, help_text='Buyruq bajarilish vaqti millisekund', null=True, verbose_name='Bajarilish vaqti (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Qurilma buyrug'i",
                'verbose_name_plural': 'Qurilma buyruqlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hikvisiondevice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hikvision qurilma', 'verbose_name_plural': 'Hikvision qurilmalar'},
        ),
        migrations.AddField(
            model_name='hikvisiondevice',
            name='auto_sync_enabled',
            field=models.BooleanField(default=True, help_text="Avtomatik sinxronizatsiya yoqilgan yoki yo'q", verbose_name='Avtomatik sinxronizatsiya'),
        ),
        migrations.AddField(
            model_name='hikvisiondevice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Qurilma o'rnatilgan filial", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='hikvisiondevice',
            name='description',
            field=models.TextField(blank=True, help_text="Qo'shimcha ma'lumotlar", null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='hikvisiondevice',
            name='device_type',
            field=models.CharField(choices=[('face_terminal', 'Yuz tanish terminali'), ('fingerprint', 'Barmoq izi skaneri'), ('card_reader', "Karta o'quvchi"), ('mixed', 'Aralash')], default='face_terminal', help_text='Qurilma texnologiyasi', max_length=20, verbose_name='Qurilma turi'),
        ),
        migrations.AddField(
            model_name='hikvisiondevice',
            name='firmware_version',
            field=models.CharField(blank=True, help_text="Qurilma dasturiy ta'minot versiyasi", max_length=50, null=True, verbose_name='Firmware versiyasi'),
        ),
        migrations.AddField(
            model_name='hikvisiondevice',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text="Qurilma bilan oxirgi muvaffaqiyatli bog'lanish", null=True, verbose_name="Oxirgi bog'lanish"),
        ),
        migrations.AddField(
            model_name='hikvisiondevice',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=15, help_text="Qancha vaqt oralig'ida ma'lumotlar sinxronlanadi", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name="Sinxronizatsiya oralig'i (daqiqa)"),
        ),
        migrations.AddField(
            model_name='synclog',
            name='error_details',
            field=models.JSONField(blank=True, help_text="Batafsil xatolik ma'lumotlari (JSON)", null=True, verbose_name='Xatolik tafsilotlari'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='metadata',
            field=models.JSONField(blank=True, help_text="Boshqa foydali ma'lumotlar", null=True, verbose_name="Qo'shimcha ma'lumot"),
        ),
        migrations.AddField(
            model_name='synclog',
            name='records_failed',
            field=models.PositiveIntegerField(default=0, help_text='Xatolik yuz bergan yozuvlar soni', verbose_name='Xatolik bilan'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('auto', 'Avtomatik'), ('manual', "Qo'lda"), ('initial', 'Dastlabki'), ('recovery', 'Qayta urinish')], default='auto', help_text='Qanday tarzda boshlangan', max_length=20, verbose_name='Sinxronizatsiya turi'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='triggered_by',
            field=models.CharField(blank=True, help_text='Sinxronizatsiyani kim/nima boshladi', max_length=100, null=True, verbose_name='Kim tomonidan'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Qurilmaning tarmoqdagi IP manzili', verbose_name='IP manzil'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Qurilma tizimda faol yoki yo'q", verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text="Ma'lumotlar oxirgi marta sinxronlangan vaqt", null=True, verbose_name='Oxirgi sinxronizatsiya'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='location',
            field=models.CharField(blank=True, help_text="Qurilma o'rnatilgan joy", max_length=200, null=True, verbose_name='Joylashuv'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='model',
            field=models.CharField(blank=True, help_text='Qurilma modeli (masalan: DS-K1T343EFWX)', max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='name',
            field=models.CharField(help_text='Qurilmaning identifikatsiya uchun nomi', max_length=100, verbose_name='Qurilma nomi'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='password',
            field=models.CharField(help_text='Qurilmaga kirish paroli', max_length=100, verbose_name='Parol'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='port',
            field=models.PositiveIntegerField(default=80, help_text='HTTP port raqami (standart: 80)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Qurilmaning zavod seriya raqami', max_length=100, null=True, unique=True, verbose_name='Seriya raqami'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Xatolik'), ('maintenance', 'Texnik xizmat'), ('syncing', 'Sinxronizatsiya')], default='offline', help_text='Qurilmaning joriy holati', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='hikvisiondevice',
            name='username',
            field=models.CharField(help_text='Qurilmaga kirish uchun foydalanuvchi nomi', max_length=50, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='device',
            field=models.ForeignKey(help_text='Sinxronizatsiya qilingan qurilma', on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='hikvision.hikvisiondevice', verbose_name='Qurilma'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Xatolik haqida qisqa xabar', null=True, verbose_name='Xatolik xabari'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Sinxronizatsiya tugagan vaqt', null=True, verbose_name='Tugagan vaqt'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='records_fetched',
            field=models.PositiveIntegerField(default=0, help_text='Qurilmadan olingan yozuvlar soni', verbose_name='Olingan yozuvlar'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='records_processed',
            field=models.PositiveIntegerField(default=0, help_text='Muvaffaqiyatli qayta ishlangan yozuvlar', verbose_name='Qayta ishlangan'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Sinxronizatsiya boshlangan vaqt', verbose_name='Boshlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('success', 'Muvaffaqiyatli'), ('partial', 'Qisman'), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilingan')], default='pending', help_text='Sinxronizatsiya holati', max_length=20, verbose_name='Holat'),
        ),
        migrations.AddIndex(
            model_name='hikvisiondevice',
            index=models.Index(fields=['branch'], name='hik_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='hikvisiondevice',
            index=models.Index(fields=['ip_address'], name='hik_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='hikvisiondevice',
            index=models.Index(fields=['status'], name='hik_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hikvisiondevice',
            index=models.Index(fields=['is_active'], name='hik_active_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['device', 'started_at'], name='sync_dev_time_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='sync_status_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['started_at'], name='sync_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='hikvisiondevice',
            constraint=models.UniqueConstraint(fields=('ip_address', 'port'), name='unique_device_endpoint'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='hikvision.hikvisiondevice', verbose_name='Qurilma'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'created_at'], name='cmd_dev_time_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['command_type'], name='cmd_type_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['is_successful'], name='cmd_success_idx'),
        ),
    ]
