# Generated by Django 6.0.1 on 2026-01-16 12:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tashkilotning umumiy nomi', max_length=200, verbose_name='Tashkilot nomi')),
                ('legal_name', models.CharField(blank=True, help_text="Rasmiy hujjatlardagi to'liq nomi", max_length=300, null=True, verbose_name='Yuridik nomi')),
                ('code', models.CharField(help_text='Qisqa unikal identifikator (masalan: MEGA, ABC)', max_length=20, unique=True, verbose_name='Kod')),
                ('inn', models.CharField(blank=True, help_text="Soliq to'lovchi identifikatsiya raqami", max_length=20, null=True, unique=True, verbose_name='INN/STIR')),
                ('logo', models.ImageField(blank=True, help_text='Tashkilot logotipi', null=True, upload_to='organizations/logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, help_text="Tashkilot haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif')),
                ('address', models.TextField(blank=True, help_text="Rasmiy ro'yxatdan o'tgan manzil", null=True, verbose_name='Yuridik manzil')),
                ('phone', models.CharField(blank=True, help_text='Asosiy aloqa telefoni', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda bo'lishi kerak", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, help_text='Asosiy email manzili', max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, help_text='Rasmiy veb-sayt manzili', null=True, verbose_name='Veb-sayt')),
                ('founded_date', models.DateField(blank=True, help_text='Kompaniya qachon tashkil etilgan', null=True, verbose_name='Tashkil etilgan sana')),
                ('industry', models.CharField(choices=[('it', 'IT va dasturlash'), ('finance', 'Moliya va bank'), ('retail', 'Chakana savdo'), ('manufacturing', 'Ishlab chiqarish'), ('healthcare', "Sog'liqni saqlash"), ('education', "Ta'lim"), ('construction', 'Qurilish'), ('transport', 'Transport va logistika'), ('agriculture', "Qishloq xo'jaligi"), ('hospitality', 'Mehmonxona va restoran'), ('telecom', 'Telekommunikatsiya'), ('energy', 'Energetika'), ('government', 'Davlat tashkiloti'), ('other', 'Boshqa')], default='other', help_text="Asosiy faoliyat yo'nalishi", max_length=30, verbose_name='Faoliyat sohasi')),
                ('employee_count', models.PositiveIntegerField(blank=True, help_text='Taxminiy jami hodimlar soni', null=True, verbose_name='Hodimlar soni')),
                ('is_active', models.BooleanField(default=True, help_text="Tashkilot tizimda faol yoki yo'q", verbose_name='Faol')),
                ('timezone', models.CharField(default='Asia/Tashkent', help_text='Tashkilotning asosiy vaqt zonasi', max_length=50, verbose_name='Vaqt zonasi')),
                ('currency', models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'AQSH dollari'), ('EUR', 'Yevro'), ('RUB', 'Rossiya rubli')], default='UZS', help_text='Asosiy hisob-kitob valyutasi', max_length=3, verbose_name='Valyuta')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], default='uz', help_text='Tizimning asosiy tili', max_length=5, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='org_code_idx'), models.Index(fields=['is_active'], name='org_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_threshold_minutes', models.PositiveIntegerField(default=5, help_text='Necha daqiqadan keyin kechikish hisoblanadi', validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Kechikish chegarasi (daqiqa)')),
                ('early_leave_threshold_minutes', models.PositiveIntegerField(default=5, help_text='Necha daqiqadan oldin ketsa erta ketish hisoblanadi', validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Erta ketish chegarasi (daqiqa)')),
                ('overtime_calculation_enabled', models.BooleanField(default=True, help_text="Qo'shimcha ish vaqtini hisoblash yoqilgan", verbose_name='Overtime hisoblash')),
                ('half_day_threshold_hours', models.PositiveIntegerField(default=4, help_text='Necha soatdan kam ishlasa yarim kun hisoblanadi', validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Yarim kun chegarasi (soat)')),
                ('working_days', models.JSONField(default=list, help_text="Ish kunlari ro'yxati [0-6]: 0=Dushanba, 6=Yakshanba", verbose_name='Ish kunlari')),
                ('auto_sync_interval_minutes', models.PositiveIntegerField(default=15, help_text="Qancha vaqt oralig'ida sinxronlanadi", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Avtomatik sinxronizatsiya (daqiqa)')),
                ('sync_history_days', models.PositiveIntegerField(default=30, help_text='Necha kunlik tarix saqlanadi', verbose_name='Sinxronizatsiya tarixi (kun)')),
                ('notification_email', models.EmailField(blank=True, help_text='Muhim xabarlar uchun email', max_length=254, null=True, verbose_name='Bildirishnoma email')),
                ('send_daily_report', models.BooleanField(default=False, help_text='Har kuni avtomatik hisobot yuborish', verbose_name='Kunlik hisobot yuborish')),
                ('send_late_notifications', models.BooleanField(default=True, help_text='Kechikganlar haqida xabar yuborish', verbose_name='Kechikish xabari')),
                ('allow_remote_work', models.BooleanField(default=False, help_text='Hodimlar masofadan ishlashi mumkinmi', verbose_name='Masofadan ishlash')),
                ('require_photo_on_check', models.BooleanField(default=False, help_text='Kirish/chiqishda rasm olish majburiymi', verbose_name='Rasm talab qilish')),
                ('allow_manual_attendance', models.BooleanField(default=True, help_text="Admin qo'lda davomat kiritishi mumkinmi", verbose_name="Qo'lda davomat")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Tashkilot sozlamasi',
                'verbose_name_plural': 'Tashkilot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Filialning to'liq nomi", max_length=200, verbose_name='Filial nomi')),
                ('code', models.CharField(help_text='Unikal identifikator (masalan: TSH-01, SAM-02)', max_length=20, verbose_name='Filial kodi')),
                ('branch_type', models.CharField(choices=[('head_office', 'Bosh ofis'), ('regional_office', 'Hududiy ofis'), ('branch', 'Filial'), ('warehouse', 'Omborxona'), ('factory', 'Zavod/Fabrika'), ('store', "Do'kon"), ('service_center', 'Xizmat markazi')], default='branch', help_text="Filialning vazifasi bo'yicha turi", max_length=20, verbose_name='Filial turi')),
                ('address', models.TextField(blank=True, help_text="To'liq ko'cha manzili", null=True, verbose_name='Manzil')),
                ('city', models.CharField(blank=True, help_text='Shahar nomi', max_length=100, null=True, verbose_name='Shahar')),
                ('region', models.CharField(blank=True, help_text='Viloyat yoki hudud nomi', max_length=100, null=True, verbose_name='Viloyat/Hudud')),
                ('country', models.CharField(default="O'zbekiston", help_text='Davlat nomi', max_length=100, verbose_name='Davlat')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS koordinata (latitude)', max_digits=9, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS koordinata (longitude)', max_digits=9, null=True, verbose_name='Uzunlik')),
                ('phone', models.CharField(blank=True, help_text='Asosiy aloqa telefoni', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda bo'lishi kerak", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, help_text='Filial email manzili', max_length=254, null=True, verbose_name='Email')),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0), help_text='Filialning standart ish boshlanish vaqti', verbose_name='Ish boshlanish vaqti')),
                ('work_end_time', models.TimeField(default=datetime.time(18, 0), help_text='Filialning standart ish tugash vaqti', verbose_name='Ish tugash vaqti')),
                ('timezone', models.CharField(default='Asia/Tashkent', help_text='Filialning vaqt zonasi', max_length=50, verbose_name='Vaqt zonasi')),
                ('is_active', models.BooleanField(default=True, help_text="Filial faol yoki yo'q", verbose_name='Faol')),
                ('is_head_office', models.BooleanField(default=False, help_text='Bu filial bosh ofis hisoblanadimi', verbose_name='Bosh ofis')),
                ('description', models.TextField(blank=True, help_text="Filial haqida qo'shimcha ma'lumot", null=True, verbose_name='Tavsif')),
                ('established_date', models.DateField(blank=True, help_text='Filial qachon ochilgan', null=True, verbose_name='Ochilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('parent', models.ForeignKey(blank=True, help_text="Ierarxik bog'lanish (masalan: hududiy ofis -> bosh ofis)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.branch', verbose_name='Yuqori filial')),
                ('organization', models.ForeignKey(help_text='Filial tegishli tashkilot', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['organization', 'name'],
                'indexes': [models.Index(fields=['organization', 'code'], name='branch_org_code_idx'), models.Index(fields=['is_active'], name='branch_active_idx'), models.Index(fields=['branch_type'], name='branch_type_idx'), models.Index(fields=['city'], name='branch_city_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='unique_branch_code_per_org')],
            },
        ),
    ]
