# Generated by Django 5.0 on 2026-01-19 07:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Obyekt ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="O'zgarish vaqti", verbose_name='Vaqt')),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', "O'zgartirildi"), ('delete', "O'chirildi"), ('submit', 'Yuborildi'), ('approve', 'Tasdiqlandi'), ('reject', 'Rad etildi'), ('lock', 'Bloklandi'), ('unlock', 'Blok ochildi')], help_text='Qanday harakat bajarildi', max_length=20, verbose_name='Harakat')),
                ('field_changes', models.JSONField(default=dict, help_text="O'zgargan maydonlar va ularning eski/yangi qiymatlari", verbose_name="Maydon o'zgarishlari")),
                ('comment', models.TextField(help_text="O'zgarish sababi (MAJBURIY)", verbose_name='Izoh')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name="Brauzer ma'lumoti")),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model turi')),
                ('user', models.ForeignKey(help_text="Kim o'zgartirdi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_log', 'Can view audit logs')],
            },
        ),
        migrations.CreateModel(
            name='FieldChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Model maydoni nomi (masalan: 'calculated_salary')", max_length=100, verbose_name='Maydon nomi')),
                ('field_verbose_name', models.CharField(blank=True, help_text="Maydonning o'zbekcha nomi", max_length=200, verbose_name="O'qiladigan nom")),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Eski qiymat')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Yangi qiymat')),
                ('value_type', models.CharField(default='string', help_text='string, integer, decimal, boolean, date, datetime, json', max_length=50, verbose_name='Qiymat turi')),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_histories', to='core.auditlog', verbose_name='Audit log')),
            ],
            options={
                'verbose_name': "Maydon o'zgarish tarixi",
                'verbose_name_plural': "Maydon o'zgarish tarixlari",
                'ordering': ['field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_content_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_user_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldchangehistory',
            index=models.Index(fields=['audit_log'], name='fieldhistory_audit_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldchangehistory',
            index=models.Index(fields=['field_name'], name='fieldhistory_field_idx'),
        ),
    ]
