# Generated by Django 6.0.1 on 2026-01-16 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_fields'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '__first__'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('organization', 'Tashkilot'), ('branch', 'Filial'), ('department', "Bo'lim")], help_text='Qaysi darajada dostup beriladi', max_length=20, verbose_name='Dostup turi')),
                ('can_view', models.BooleanField(default=True, help_text="Ma'lumotlarni ko'rish huquqi", verbose_name="Ko'rish")),
                ('can_edit', models.BooleanField(default=False, help_text="Ma'lumotlarni o'zgartirish huquqi", verbose_name='Tahrirlash')),
                ('can_delete', models.BooleanField(default=False, help_text="Ma'lumotlarni o'chirish huquqi", verbose_name="O'chirish")),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='Qachon dostup berildi', verbose_name='Berilgan vaqt')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Qachon dostup tugaydi (bo'sh bo'lsa - abadiy)", null=True, verbose_name='Amal qilish muddati')),
                ('is_active', models.BooleanField(default=True, help_text='Dostup faolmi', verbose_name='Faol')),
                ('notes', models.TextField(blank=True, help_text="Dostup haqida qo'shimcha ma'lumot", null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi dostupi',
                'verbose_name_plural': 'Foydalanuvchi dostuplari',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Aloqa uchun telefon raqami', max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('hr', 'HR Manager'), ('viewer', 'Viewer')], default='viewer', help_text='Foydalanuvchining tizimda huquqlari', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_active_idx'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Dostup beriladigan filial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Dostup beriladigan bo'lim", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='employees.department', verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Dostupni kim berdi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Kim berdi'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Dostup beriladigan tashkilot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='core.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='user',
            field=models.ForeignKey(help_text='Kimga dostup berilmoqda', on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['user', 'access_type'], name='useraccess_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['is_active'], name='useraccess_active_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['expires_at'], name='useraccess_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('user', 'organization'), name='unique_user_organization_access'),
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('user', 'branch'), name='unique_user_branch_access'),
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('user', 'department'), name='unique_user_department_access'),
        ),
    ]
