# Generated by Django 5.0 on 2026-01-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccess_alter_user_options_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Oddiy xodim'), ('manager', "Bo'lim boshlig'i"), ('accountant', 'Buxgalter'), ('chief_accountant', 'Glavniy buxgalter'), ('superuser', 'Administrator'), ('admin', 'Administrator (legacy)'), ('hr', 'HR Manager (legacy)'), ('viewer', 'Viewer (legacy)')], default='viewer', help_text='Foydalanuvchining tizimda huquqlari', max_length=20, verbose_name='Rol'),
        ),
    ]
