# Generated by Django 6.0.1 on 2026-01-16 12:14

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'ID karta'), ('diploma', 'Diplom'), ('certificate', 'Sertifikat'), ('contract', 'Shartnoma'), ('license', 'Litsenziya'), ('medical', "Tibbiy ma'lumotnoma"), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Hujjat turi')),
                ('title', models.CharField(help_text='Hujjatning qisqa nomi', max_length=200, verbose_name='Hujjat nomi')),
                ('document_number', models.CharField(blank=True, help_text='Hujjatning seriya va raqami', max_length=100, null=True, verbose_name='Hujjat raqami')),
                ('file', models.FileField(blank=True, help_text='Hujjat fayli (PDF, JPG, PNG)', null=True, upload_to='employees/documents/%Y/%m/', verbose_name='Fayl')),
                ('issue_date', models.DateField(blank=True, help_text='Hujjat qachon berilgan', null=True, verbose_name='Berilgan sana')),
                ('expiry_date', models.DateField(blank=True, help_text='Hujjat qachongacha amal qiladi', null=True, verbose_name='Amal qilish muddati')),
                ('issued_by', models.CharField(blank=True, help_text='Hujjatni bergan organ/tashkilot', max_length=200, null=True, verbose_name='Kim tomonidan berilgan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
            ],
            options={
                'verbose_name': 'Hodim hujjati',
                'verbose_name_plural': 'Hodim hujjatlari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['branch', 'sort_order', 'name'], 'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['department', '-level', 'name'], 'verbose_name': 'Lavozim', 'verbose_name_plural': 'Lavozimlar'},
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Bo'lim tegishli filial", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='department',
            name='budget_code',
            field=models.CharField(blank=True, help_text='Moliyaviy hisobot uchun byudjet kodi', max_length=50, null=True, verbose_name='Byudjet kodi'),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Qisqa identifikator (masalan: IT, HR, FIN)', max_length=20, null=True, verbose_name="Bo'lim kodi"),
        ),
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost center kodi', max_length=50, null=True, verbose_name='Xarajat markazi'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text="Bo'limning rahbari", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee', verbose_name="Bo'lim boshlig'i"),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Bo'lim faol yoki arxivlangan", verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Ierarxik tuzilma uchun', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='employees.department', verbose_name="Yuqori bo'lim"),
        ),
        migrations.AddField(
            model_name='department',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text="Ro'yxatdagi tartib raqami", verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Yashash manzili', null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Hodimning tug'ilgan sanasi", null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Hodim ishlaydigan filial', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text="Favqulodda holatlarda bog'lanish uchun shaxs", max_length=200, null=True, verbose_name='Favqulodda aloqa (ism)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Favqulodda aloqa telefon raqami', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda bo'lishi kerak: '+998901234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Favqulodda aloqa (telefon)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', "To'liq stavka"), ('part_time', 'Yarim stavka'), ('contract', 'Shartnoma'), ('intern', 'Stajirovka'), ('remote', 'Masofadan')], default='full_time', help_text="To'liq stavka, yarim stavka va h.k.", max_length=20, verbose_name='Ish turi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], help_text='Hodimning jinsi', max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Hodimning bevosita rahbari', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='Rahbar'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha ma'lumotlar", null=True, verbose_name='Izohlar'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Shaxsiy email manzili', max_length=254, null=True, verbose_name='Shaxsiy email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, help_text="Qo'shimcha shaxsiy telefon", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda bo'lishi kerak: '+998901234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Shaxsiy telefon'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personnel_number',
            field=models.CharField(blank=True, help_text='Ichki tabel raqami', max_length=20, null=True, verbose_name='Tabel raqami'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, help_text='Sinov muddati qachon tugaydi', null=True, verbose_name='Sinov muddati tugashi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, help_text="Ishdan bo'shatilgan sana (agar mavjud bo'lsa)", null=True, verbose_name="Bo'shatilgan sana"),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.TextField(blank=True, help_text="Ishdan bo'shatilish sababi", null=True, verbose_name="Bo'shatilish sababi"),
        ),
        migrations.AddField(
            model_name='employee',
            name='use_branch_schedule',
            field=models.BooleanField(default=True, help_text="True bo'lsa, filialning standart ish vaqti ishlatiladi", verbose_name='Filial jadvalini ishlatish'),
        ),
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.CharField(blank=True, help_text='Qisqa identifikator', max_length=20, null=True, verbose_name='Lavozim kodi'),
        ),
        migrations.AddField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, help_text="Lavozim vazifalari va mas'uliyatlari", null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='position',
            name='headcount',
            field=models.PositiveIntegerField(default=1, help_text='Bu lavozim uchun rejalashtirilgan hodimlar soni', verbose_name='Shtat soni'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Lavozim faol yoki arxivlangan', verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Bu lavozim boshqaruv vazifasini bajaradimi', verbose_name='Boshqaruv lavozimi'),
        ),
        migrations.AddField(
            model_name='position',
            name='level',
            field=models.IntegerField(choices=[(1, 'Stajyor'), (2, 'Junior'), (3, 'Middle'), (4, 'Senior'), (5, 'Lead/Boshlovchi'), (6, 'Menejer'), (7, 'Direktor'), (8, 'Vitse-prezident'), (9, 'C-Level'), (10, 'Bosh direktor')], default=3, help_text='Lavozim darajasi (1-10)', verbose_name='Daraja'),
        ),
        migrations.AddField(
            model_name='position',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lavozim uchun maksimal oylik', max_digits=12, null=True, verbose_name='Maksimal ish haqi'),
        ),
        migrations.AddField(
            model_name='position',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lavozim uchun minimal oylik', max_digits=12, null=True, verbose_name='Minimal ish haqi'),
        ),
        migrations.AddField(
            model_name='position',
            name='requirements',
            field=models.TextField(blank=True, help_text="Lavozim uchun zarur bilim va ko'nikmalar", null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text="Bo'lim haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text="Bo'limning to'liq nomi", max_length=100, verbose_name="Bo'lim nomi"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Hodim ishlaydigan bo'lim", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Ish email manzili', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(help_text='Hikvision qurilmasidagi unikal identifikator', max_length=50, unique=True, verbose_name='Hodim ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text='Hodimning ismi', max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(help_text='Ishga qabul qilingan sana', verbose_name='Ishga qabul sanasi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Hodimning familiyasi', max_length=100, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Hodimning otasining ismi', max_length=100, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Asosiy telefon raqami', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda bo'lishi kerak: '+998901234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Hodimning rasmi', null=True, upload_to='employees/photos/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Hodimning lavozimi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('on_leave', "Ta'tilda"), ('probation', 'Sinov muddati'), ('terminated', "Bo'shatilgan")], default='active', help_text='Hodimning joriy holati', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Kunlik ish tugash vaqti', verbose_name='Ish tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Kunlik ish boshlanish vaqti', verbose_name='Ish boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(help_text="Lavozim tegishli bo'lim", on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.department', verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text="Lavozimning to'liq nomi", max_length=100, verbose_name='Lavozim nomi'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['branch', 'code'], name='dept_branch_code_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='dept_active_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='emp_id_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch'], name='emp_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='emp_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='emp_name_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['department'], name='pos_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['level'], name='pos_level_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['is_active'], name='pos_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='unique_dept_code_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_position_per_dept'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='Hodim'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'document_type'], name='doc_emp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['expiry_date'], name='doc_expiry_idx'),
        ),
    ]
